web:
  build: .
  restart: always
  command: npm start
  expose:
    - "3000"
  environment:
    - VIRTUAL_HOST=math.sander.ee
    - LETSENCRYPT_HOST=math.sander.ee
    - LETSENCRYPT_EMAIL=alex@sander.ee
